packages:
  - apps/frontend
  - apps/backend
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver
