import { ChatType, MessageType, UserRole } from '@prisma/client';
import { randomUUID } from 'crypto';

const PROFILE_PIC_URL = 'https://mdbcdn.b-cdn.net/img/new/avatars/2.webp';

const userIds = {
  alice: randomUUID(),
  bob: randomUUID(),
  charlie: randomUUID(),
  diana: randomUUID(),
  nick: randomUUID(),
  emma: randomUUID(),
  oliver: randomUUID(),
  sophia: randomUUID(),
  liam: randomUUID(),
  ava: randomUUID(),
  mia: randomUUID(),
  noah: randomUUID(),
  lucas: randomUUID(),
  elijah: randomUUID(),
  grace: randomUUID(),
  harper: randomUUID(),
};

const profileIds = {
  alice: randomUUID(),
  bob: randomUUID(),
  charlie: randomUUID(),
  diana: randomUUID(),
  nick: randomUUID(),
  emma: randomUUID(),
  oliver: randomUUID(),
  sophia: randomUUID(),
  liam: randomUUID(),
  ava: randomUUID(),
  mia: randomUUID(),
  noah: randomUUID(),
  lucas: randomUUID(),
  elijah: randomUUID(),
  grace: randomUUID(),
  harper: randomUUID(),
};

const chatIds = {
  ketchupStains: randomUUID(),
  coolestKats: randomUUID(),
  groupChat1: randomUUID(),
  bigGroup2: randomUUID(),
  directChat1: randomUUID(),
  directChat2: randomUUID(),
};
export const usersData = [
  {
    id: userIds.alice,
    email: 'alice@example.com',
    password: 'alicepw',
    role: UserRole.USER,
  },
  {
    id: userIds.bob,
    email: 'bob@example.com',
    password: 'bobpw',
    role: UserRole.USER,
  },
  {
    id: userIds.charlie,
    email: 'charlie@example.com',
    password: 'charliepw',
    role: UserRole.USER,
  },
  {
    id: userIds.diana,
    email: 'diana@example.com',
    password: 'dianapw',
    role: UserRole.USER,
  },
  {
    id: userIds.nick,
    email: 'email@gmail.com',
    password: 'fakePass1!',
    role: UserRole.ADMIN,
  },
  {
    id: userIds.emma,
    email: 'emma@example.com',
    password: 'emmapw',
    role: UserRole.USER,
  },
  {
    id: userIds.oliver,
    email: 'oliver@example.com',
    password: 'oliverpw',
    role: UserRole.USER,
  },
  {
    id: userIds.sophia,
    email: 'sophia@example.com',
    password: 'sophiapw',
    role: UserRole.USER,
  },
  {
    id: userIds.liam,
    email: 'liam@example.com',
    password: 'liampw',
    role: UserRole.USER,
  },
  {
    id: userIds.ava,
    email: 'ava@example.com',
    password: 'avapw',
    role: UserRole.USER,
  },
  {
    id: userIds.mia,
    email: 'mia@example.com',
    password: 'miapw',
    role: UserRole.USER,
  },
  {
    id: userIds.noah,
    email: 'noah@example.com',
    password: 'noahpw',
    role: UserRole.USER,
  },
  {
    id: userIds.lucas,
    email: 'lucas@example.com',
    password: 'lucaspw',
    role: UserRole.USER,
  },
  {
    id: userIds.elijah,
    email: 'elijah@example.com',
    password: 'elijahpw',
    role: UserRole.USER,
  },
  {
    id: userIds.grace,
    email: 'grace@example.com',
    password: 'gracepw',
    role: UserRole.USER,
  },
  {
    id: userIds.harper,
    email: 'harper@example.com',
    password: 'harperpw',
    role: UserRole.USER,
  },
];

export const profilesData = [
  {
    id: profileIds.alice,
    firstName: 'Alice',
    lastName: 'Smith',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.alice,
    friends: [profileIds.bob, profileIds.charlie, profileIds.nick],
  },
  {
    id: profileIds.bob,
    firstName: 'Bob',
    lastName: 'Jones',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.bob,
    friends: [profileIds.alice, profileIds.diana, profileIds.nick],
  },
  {
    id: profileIds.charlie,
    firstName: 'Charlie',
    lastName: 'Brown',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.charlie,
    friends: [profileIds.alice, profileIds.diana],
  },
  {
    id: profileIds.diana,
    firstName: 'Diana',
    lastName: 'Prince',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.diana,
    friends: [profileIds.bob, profileIds.charlie],
  },
  {
    id: profileIds.nick,
    firstName: 'Nick',
    lastName: 'Smith',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.nick,
    friends: [
      profileIds.alice,
      profileIds.bob,
      profileIds.emma,
      profileIds.oliver,
      profileIds.sophia,
      profileIds.liam,
      profileIds.ava,
      profileIds.mia,
      profileIds.noah,
      profileIds.lucas,
      profileIds.elijah,
      profileIds.grace,
      profileIds.harper,
    ],
  },
  {
    id: profileIds.emma,
    firstName: 'Emma',
    lastName: 'Johnson',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.emma,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.oliver,
    firstName: 'Oliver',
    lastName: 'Williams',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.oliver,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.sophia,
    firstName: 'Sophia',
    lastName: 'Martinez',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.sophia,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.liam,
    firstName: 'Liam',
    lastName: 'Davis',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.liam,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.ava,
    firstName: 'Ava',
    lastName: 'Garcia',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.ava,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.mia,
    firstName: 'Mia',
    lastName: 'Rodriguez',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.mia,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.noah,
    firstName: 'Noah',
    lastName: 'Lee',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.noah,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.lucas,
    firstName: 'Lucas',
    lastName: 'Walker',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.lucas,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.elijah,
    firstName: 'Elijah',
    lastName: 'Hall',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.elijah,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.grace,
    firstName: 'Grace',
    lastName: 'Allen',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.grace,
    friends: [profileIds.nick],
  },
  {
    id: profileIds.harper,
    firstName: 'Harper',
    lastName: 'Young',
    avatarUrl: PROFILE_PIC_URL,
    userId: userIds.harper,
    friends: [profileIds.nick],
  },
];

export const chatsData = [
  {
    id: chatIds.ketchupStains,
    name: 'Ketchup Stains',
    creatorId: profileIds.alice,
    type: ChatType.GROUP,
    participantIds: [profileIds.alice, profileIds.bob, profileIds.nick],
    groupPictureUrl:
      'https://t3.ftcdn.net/jpg/04/79/93/20/360_F_479932092_BmeQGwL1ljKI368UJVlIwczA8MtjbBnj.jpg',
  },
  {
    id: chatIds.coolestKats,
    name: 'The Coolest Kats',
    creatorId: profileIds.charlie,
    type: ChatType.GROUP,
    participantIds: [profileIds.charlie, profileIds.diana, profileIds.nick],
    groupPictureUrl:
      'https://media.istockphoto.com/id/1322842973/photo/diverse-business-people-putting-their-hands-together-in-cirle.jpg?s=612x612&w=0&k=20&c=9BAYCv8tAsgYPQdTsFxLzLJsmt6tGYE5Etwd63OccxQ=',
  },
  {
    id: chatIds.groupChat1,
    name: 'GROUP CHAT 1',
    creatorId: profileIds.charlie,
    type: ChatType.GROUP,
    participantIds: [
      profileIds.charlie,
      profileIds.diana,
      profileIds.alice,
      profileIds.bob,
      profileIds.nick,
    ],
  },
  {
    id: chatIds.bigGroup2,
    creatorId: profileIds.charlie,
    type: ChatType.GROUP,
    participantIds: [
      profileIds.charlie,
      profileIds.diana,
      profileIds.alice,
      profileIds.nick,
      profileIds.bob,
    ],
  },
  {
    id: chatIds.directChat1,
    creatorId: profileIds.nick,
    type: ChatType.DIRECT,
    participantIds: [profileIds.alice, profileIds.nick],
  },
  {
    id: chatIds.directChat2,
    creatorId: profileIds.alice,
    type: ChatType.DIRECT,
    participantIds: [profileIds.charlie, profileIds.nick],
  },
];

export const messagesData = [
  // Ketchup Stains chat
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Hey Bob!',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.IMAGE,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/4/4d/Cat_November_2010-1a.jpg',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.IMAGE,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/4/4d/Cat_November_2010-1a.jpg',
    senderId: profileIds.bob,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.IMAGE,
    imageUrl:
      'https://plus.unsplash.com/premium_photo-1673967831980-1d377baaded2?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0c3xlbnwwfHwwfHx8MA%3D%3D',
    senderId: profileIds.nick,
    chatId: chatIds.coolestKats,
  },
  {
    id: randomUUID(),
    type: MessageType.IMAGE,
    imageUrl:
      'https://plus.unsplash.com/premium_photo-1673967831980-1d377baaded2?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0c3xlbnwwfHwwfHx8MA%3D%3D',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },

  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'How are you doing today?',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Did you see the game last night?',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Hey Alice! How are you?',
    senderId: profileIds.bob,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Doing well, just had lunch.',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Nice! What did you eat?',
    senderId: profileIds.bob,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Sandwich with way too much ketchup.',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'And a side of fries!',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Classic Alice move 😂',
    senderId: profileIds.bob,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'You know me!',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Let’s hang out later?',
    senderId: profileIds.bob,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Sure! 5pm at the park?',
    senderId: profileIds.alice,
    chatId: chatIds.ketchupStains,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'See you there!',
    senderId: profileIds.bob,
    chatId: chatIds.ketchupStains,
  },

  // Coolest Kats chat
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Hey Diana, did you finish the project?',
    senderId: profileIds.charlie,
    chatId: chatIds.coolestKats,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'I was working on it all night.',
    senderId: profileIds.charlie,
    chatId: chatIds.coolestKats,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Almost! Just need to add the final touches.',
    senderId: profileIds.diana,
    chatId: chatIds.coolestKats,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Let me know if you need help.',
    senderId: profileIds.charlie,
    chatId: chatIds.coolestKats,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Thanks, Charlie! You’re the best.',
    senderId: profileIds.diana,
    chatId: chatIds.coolestKats,
  },

  // Group Chat 1
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Hey everyone!',
    senderId: profileIds.charlie,
    chatId: chatIds.groupChat1,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Hi Charlie!',
    senderId: profileIds.bob,
    chatId: chatIds.groupChat1,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'What’s up?',
    senderId: profileIds.alice,
    chatId: chatIds.groupChat1,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Ready for the game tonight?',
    senderId: profileIds.diana,
    chatId: chatIds.groupChat1,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Absolutely! Go team!',
    senderId: profileIds.charlie,
    chatId: chatIds.groupChat1,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Let’s win this!',
    senderId: profileIds.charlie,
    chatId: chatIds.groupChat1,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'We got this!',
    senderId: profileIds.charlie,
    chatId: chatIds.groupChat1,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Let’s win this!',
    senderId: profileIds.bob,
    chatId: chatIds.groupChat1,
  },

  // Big Group 2
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Morning all!',
    senderId: profileIds.diana,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Good morning!',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Anyone up for coffee?',
    senderId: profileIds.charlie,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Always!',
    senderId: profileIds.diana,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Count me in ☕',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },

  // ...more messages for realism...
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Hello Diana!',
    senderId: profileIds.charlie,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'How was your weekend?',
    senderId: profileIds.diana,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Pretty good! Went hiking.',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Nice! Where to?',
    senderId: profileIds.charlie,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Bear Mountain.',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'That’s awesome!',
    senderId: profileIds.diana,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'We should all go next time.',
    senderId: profileIds.charlie,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'I’m in!',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Me too!',
    senderId: profileIds.diana,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'What’s everyone doing for lunch?',
    senderId: profileIds.charlie,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Ordering pizza.',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Save me a slice!',
    senderId: profileIds.diana,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Of course!',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Anyone want to play chess later?',
    senderId: profileIds.charlie,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'I’m game!',
    senderId: profileIds.diana,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'Let’s do it!',
    senderId: profileIds.alice,
    chatId: chatIds.bigGroup2,
  },
  {
    id: randomUUID(),
    type: MessageType.TEXT,
    content: 'See you all soon!',
    senderId: profileIds.charlie,
    chatId: chatIds.bigGroup2,
  },
];
